server:
  port: 9010

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
    sqlScriptEncoding: UTF-8
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        webAllowOthers: true
  jpa:
    showSql: true
    ddlAuto: create